---
# tasks file for kvm-manage

- name: Install needed rpms on host hypervisor
  ansible.builtin.dnf:
    name:
      - guestfs-tools
      - python3-libvirt
      - virt-top
    state: present
  become: true

- name: Create Fedora VM
  include_tasks: create-fedora.yml
  vars:
    ram_mb: "{{ vm.ramb }}"
    cpus: "{{ vm.cpus }}"
    net: "{{ vm.net }}"
    os: "{{ vm.os }}"
    root_pass: "{{ vm.root_pass }}"
    root_ssh_key: "{{ vm.root_ssh_key }}"
    super_user: "{{ vm.super_user }}"
    super_user_pass: "{{ vm.super_user_pass}}"
    super_user_ssh_key: "{{ vm.super_user_ssh_key }}"
  loop: "{{ vms|flatten(levels=1) }}"
  loop_control:
    loop_var: vm
  when: (vm.state |default('present', true)) == 'present'

- name: Nuke a vm
  include_tasks: nuke-vm.yml
  loop: "{{ vms|flatten(levels=1) }}"
  loop_control:
    loop_var: vm
  when: (vm.state |default('present', true)) == 'absent'
