---
# tasks file for kvm-manage

- name: Install needed rpms on host hypervisor
  ansible.builtin.dnf:
    name:
      - guestfs-tools
      - python3-libvirt
      - virt-top
    state: present
  become: true

- name: Spit out a var for testing
  ansible.builtin.debug:
    msg: "{{ vm.root_pass }}"

- name: Create Fedora VM
  include_tasks: create-fedora.yml
  vars:
    root_pass: "{{ vm.root_pass }}"
  loop: "{{ vms|flatten(levels=1) }}"
  loop_control:
    loop_var: vm
  when: (vm.state |default('present', true)) == 'present'

- name: Nuke a vm
  include_tasks: nuke-vm.yml
  loop: "{{ vms|flatten(levels=1) }}"
  loop_control:
    loop_var: vm
  when: (vm.state |default('present', true)) == 'absent'
