---
- name: Destroy the vm
  community.libvirt.virt:
    command: destroy
    name: "{{ vm.name }}"
  ignore_errors: true

- name: Undefine the vm
  community.libvirt.virt:
    command: undefine
    name: "{{ vm.name }}"
  ignore_errors: true

- name: Delete the image file
  ansible.builtin.file:
    path: "{{ libvirt_pool_dir }}/{{ vm.name }}.qcow2"
    state: absent
